name: Swift

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild clean test -project 'PostFeed.xcodeproj' -scheme 'PostFeed' -destination "platform=iOS Simulator,name=iPhone 13,OS=latest"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
